[tools]
php = "8.5.5"

[tasks.install-composer]
run = """
if ! command -v composer >/dev/null 2>&1; 
then
  echo "Installing Composer ..."

  EXPECTED_CHECKSUM="$(php -r 'copy("https://composer.github.io/installer.sig", "php://stdout");')"
  php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
  ACTUAL_CHECKSUM="$(php -r "echo hash_file('sha384', 'composer-setup.php');")"

  if [ "$EXPECTED_CHECKSUM" != "$ACTUAL_CHECKSUM" ]
  then
      echo 'ERROR: Invalid installer checksum'
      rm composer-setup.php
      exit 1
  fi

  php composer-setup.php --quiet
  rm -f composer-setup.php composer.phar
  echo "Composer installed"
else
  echo "Composer already installed"
fi
"""
